day2/auction-site-devise/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	get '/', to: 'products#index'
    get '/products/', to: 'products#index'
    get '/products/:id', to: 'products#details', as: :products_details

    post '/products/:product_id/reviews/', to: 'reviews#create', as: :product_reviews
    delete '/products/:product_id/reviews/:id', to: 'reviews#delete', as: :product_review

    resources :users, except: [ :edit, :update ] do
      resources :products, except: [:edit, :update, :index]
    end

    post '/products/:product_id/bids', to: 'bids#create', as: :product_bids

    root 'products#index'
end

day2/auction-site-devise/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

day2/auction-site-devise/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validate :amount_cannot_be_under_product_min, :amount_cannot_be_under_highest_bid, :user_cannot_bid_their_own_product
  validate :bid_time_expired

  def bid_time_expired
    if Time.now > product.deadline
      errors.add(:product, "Can´t bid to an expired product")
    end
  end

  def amount_cannot_be_under_product_min
  	if amount < product.min_bid
  		errors.add(:amount, "can't be under min starter product bid")
  	end
  end

  def amount_cannot_be_under_highest_bid
  	if amount <= product.highest_bid_amount
  		errors.add(:amount, "can't be under or equal to highest bid")
  	end
  end

  def user_cannot_bid_their_own_product
  	if product.user == user
  		errors.add(:user, "user can´t bid their own product")
  	end
  end

  def winner_bid?
    (self.product.highest_bid_amount == self.amount) if self.product.deadline_rearched?
  end

end

day2/auction-site-devise/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bids
  has_many :reviews

  validates :min_bid, presence: true

  def deadline_rearched?
  	Time.now > deadline
  end

  def highest_bid_amount
  	max_bid = bids.max{ |a,b| a.amount <=> b.amount }
  	max_bid ? max_bid.amount : self.min_bid
	#bids.max{ |a,b| a.amount <=> b.amount }.amount || self.min_bid
  end
end

day2/auction-site-devise/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

day2/auction-site-devise/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :products
	has_many :bids
	has_many :reviews

	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
end

day2/auction-site-devise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end

end

day2/auction-site-devise/app/controllers/bids_controller.rb
class BidsController < ApplicationController
	def create
		my_user 	= User.find_by(email: params[:email])
		@my_product = Product.find_by(params[:product_id])
		@reviews    = @my_product.reviews
		@bids 		= @my_product.bids
		@my_bid 	= Bid.new(amount: params[:amount], product_id: params[:product_id])

		if my_user && (@my_bid.user_id = my_user.id) && @my_bid.save
			redirect_to '/'
		else
			render "products/details"
		end
	end
end

day2/auction-site-devise/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@my_products = Product.all
	end

	def show
		@my_product = Product.find_by_id(params[:id])
		@my_user = @my_product.user
	end

	def new
		@my_user = User.find_by_id(params[:user_id])
		@my_product = @my_user.products.new
	end

	def create
		@my_user = User.find_by_id(params[:user_id])
		@my_user.products.new(
			title: params[:product][:title],
			description: params[:product][:description],
			deadline: params[:product][:deadline], min_bid: params[:product][:min_bid])

		if @my_user.save
			redirect_to("/users/#{@my_user.id}/products")
		else
			@my_product = @my_user.products.new
			render "new"
		end
	end

	def destroy
		my_user = User.find_by_id(params[:user_id])
		my_product = my_user.products.find_by_id(params[:id])
		my_product.destroy

		redirect_to user_products_path(my_user)
	end

	def details
		@my_product = Product.find_by_id(params[:id])
		@bids = @my_product.bids.all
		@reviews = @my_product.reviews.all
		@my_bid = Bid.new
	end
end

day2/auction-site-devise/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :authenticate_user!, only: [:create, :delete]
	before_filter :ensure_owner, only: [:delete]

	def create
		@my_product = Product.find_by(id: params[:product_id])
		@bids = @my_product.bids
		@reviews = @my_product.reviews
		@my_product.reviews.new(description: params[:review][:description], user: current_user)
		@my_product.save
		render "products/details"
	end

	def delete
		@review.destroy
		@bids = @my_product.bids
		@reviews = @my_product.reviews	

		render "products/details"	
	end

	private

	def ensure_owner
		@my_product = Product.find_by(id: params[:product_id])
		@review = @my_product.reviews.find_by(id: params[:id])

		unless current_user.id == @review.user_id
			flash[:notice] = 'You are not allowed to delete this review!'
			redirect_to products_details_path(@my_product)
			return false
		end
	end
end

day2/auction-site-devise/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@my_users = User.all
	end

	def show
		@my_user = User.find_by_id(params[:id])
		@my_products = @my_user.products
		@my_reviews = @my_user.reviews
		@my_bids = @my_user.bids
		@my_wons = nil
	end

	def new
		@my_user = User.new
	end

	def create
		@my_user = User.new(name: params[:user][:name], email: params[:user][:email])
		if @my_user.save
			redirect_to ("/users/#{@my_user.id}")
		else
			render "new"
		end
	end

	def destroy
		my_user = User.find_by_id(params[:id])
		my_user.destroy
		redirect_to users_path	
	end


end

day2/auction-site-devise/app/helpers/application_helper.rb
module ApplicationHelper
	def short_datetime(time)
		time.to_formatted_s(:short)  
	end

	def format_datetime_fields(time)
		time.strftime("%FT%R")
	end
end

day2/auction-site-devise/app/helpers/bids_helper.rb
module BidsHelper
end

day2/auction-site-devise/app/helpers/products_helper.rb
module ProductsHelper
end

day2/auction-site-devise/app/helpers/reviews_helper.rb
module ReviewsHelper
end

day2/auction-site-devise/app/helpers/users_helper.rb
module UsersHelper
end

day2/auction-site-devise/app/views/products/details.html.erb
<div class="page-header">
	<h1><%= @my_product.title %> <small><%= short_datetime(@my_product.deadline) %></small></h1>
</div>
<p><%= @my_product.description %></p>
<div class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title">Previous bids</h3>
	</div>

	<table class="table">
    	<thead>
    		<tr>
    			<th>#</th>
    			<th>Amount</th>
    			<th>User</th>
    		</tr>
    	</thead>
    	<tbody>
    		<% @bids.each_with_index do |bid,index| %>
    		<tr class="<%= 'success' if bid.amount == @my_product.highest_bid_amount %>">
    			<th scope="row"><%= index + 1 %></th>
    			<td><%= bid.amount %></td>
    			<td><%= bid.user.name %></td>
    		</tr>
    		<% end %>
    	</tbody>
    </table>
</div>

<% unless @my_product.deadline_rearched? %>
	<%= form_tag (product_bids_path(@my_product.id)), { class: 'form-inline' } do %>
        <div class="form-group">
            <%= label_tag :amount %>
            <%= number_field_tag :amount, @my_product.highest_bid_amount+1, { class: 'form-control' } %>            
        </div>
        <div class="form-group">
            <%= label_tag :email %>
            <%= text_field_tag :email, "", { class: 'form-control' } %>            
        </div>

		<%= button_tag "Bid now!", {class: 'btn btn-success'}  %>
	<% end %>	
<% end %>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Product reviews</h3>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <% @reviews.each_with_index do |review,index| %>
            <tr>
                <th scope="row"><%= index + 1 %></th>
                <td><%= review.description %> <%= link_to "Delete", product_review_path(@my_product, review), { method: 'delete', class: "btn btn-danger" } %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<% if user_signed_in? %>
     <%= form_for(:review, url: product_reviews_path(@my_product)) do |f| %>
        <div class="form-group">
            <%= f.text_field :description, { class: "form-control"} %>
        </div>
        <%= f.button "Create", {class: "btn btn-success"} %>
     <% end %>       
<% end %>

day2/auction-site-devise/app/views/products/index.html.erb
<div class="row">
	<div class="col-md-9">
		<section>
	    	<div class="list-group">
				<h2>Products</h2>
	  			<% @my_products.each do |product| %>
			  		<a href=<%= products_details_path(product) %> class="list-group-item">
			  		<h4>
				    	<span class="label label-success datetime-margin">
				    		<%= short_datetime(product.deadline) %>
				    		<span class="glyphicon glyphicon-hourglass"></span>
				    	</span>
				    	<%= product.title %>
			    	</h4>
			  		</a>
	  			<% end %>
			</div>   
		</section>
	</div>
</div>

day2/auction-site-devise/app/views/products/new.html.erb
<div class="page-header">
	<h1>Add product for <%= @my_user.name %></h1>	
</div>

<% if @my_product.errors.any? %>
	<ul>
		<% @my_product.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
	
<% end %>

<div class="row">
	<div class="col-md-9">
		<%= form_for [@my_user, @my_product] do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, {class: "form-control"} %>
			</div>
			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, {class: "form-control"} %>
			</div>
			<div class="form-group">
				<%= f.label :min_bid %>
				<%= f.number_field :min_bid, {class: "form-control"} %>
			</div>
			<div class="form-group">
				<%= f.label :deadline %>
				<%= f.datetime_field :deadline, {value: format_datetime_fields(1.days.from_now), class: "form-control"} %>
			</div>
				<%= f.button "Create", {class: "btn btn-success"} %>
		<% end %>		
	</div>
</div>

day2/auction-site-devise/app/views/products/show.html.erb
<div class="page-header">
	<h1><%= @my_product.title %> <small><%= short_datetime(@my_product.deadline) %></small></h1>
</div>
<%= link_to "User profile", user_path(@my_user), {class: "btn btn-primary"} %>
<p class="lead"><%= @my_product.description %></p>

day2/auction-site-devise/app/views/users/index.html.erb
<div class="row">
	<div class="col-md-9">
		<section>
			<div class="list-group">
				<h1>
					Users <span class="pull-right"><%= link_to "New User", new_user_path, {class: "btn btn-primary"} %></span>
				</h1>
				<ul class="list-group">
					<% @my_users.each do |user| %>
						<li class="list-group-item clearfix">
						<span class="glyphicon glyphicon-user"></span>
							<span><%= user.name %></span>
							<span class="pull-right">
								<%= link_to 'Show', user_path(user), {class: "btn btn-primary"} %>
								<%= link_to 'Delete', { data: user_path(user), method: :delete}, {class: "btn btn-danger"} %>	
							</span>
														
						</li>
					<% end %>
				</ul>
			</div>
			
		</section>
	</div>
</div>

day2/auction-site-devise/app/views/users/new.html.erb
<div class="page-header">
	<h1>Add new User</h1>
</div>

<% if @my_user.errors.any? %>
	<ul>
		<% @my_user.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
	
<% end %>

<div class="row">
	<div class="col-md-9">
		<%= form_for(@my_user, html: {class: "form-inline"}) do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, {class: "form-control"} %>	
		</div>
		<div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email, {class: "form-control"} %>	
		</div>
		<%= f.button "Create", {class: "btn btn-success"} %>
<% end %>
	</div>

</div>

day2/auction-site-devise/app/views/users/show.html.erb
<div class="page-header">
	<h1><%= @my_user.name %> <small><%= @my_user.email %></small></h1>
</div>
<div class="nav">
	<%= link_to 'New product', new_user_product_path(@my_user), {class: "btn btn-primary"} %>
</div>
<div class="row">
	<div class="col-md-9">
		<section>
			<h2>My products</h2>
			<div class="list-group">
				<% @my_products.each do |product| %>
			  		<span class="list-group-item clearfix">
			  			<h4>
					    	<span class="label label-success datetime-margin">
					    		<%= short_datetime(product.deadline) %>
					    		<span class="glyphicon glyphicon-hourglass"></span>
					    	</span>
				    		<span><%= product.title %></span>
					    	<span class="pull-right">
					    		<%= link_to 'Show', user_product_path(@my_user, product), {class: "btn btn-primary"}  %>
								<%= link_to 'Delete', { data: user_product_path(@my_user, product), method: :delete}, 
									{class: "btn btn-danger"}  %>
				    		</span>

			    		</h4>
			  		</span>
				<% end %>
			</div>
		</section>
		<section>
			<h2>Won products</h2>
			<div class="list-group">
			<% @my_bids.each do |bid| %>
				<% if bid.winner_bid? %>
					<span class="list-group-item">
						<h4>
							<span><%= bid.product.title %></span>
						</h4>
					</span>
				<% end %>
			<% end %>
				
			</div>
		</section>
		<section>
			<h2>Writted reviews</h2>
			<div class="list-group">
			<% @my_reviews.each do |review| %>

					<span class="list-group-item">
						<h4>
							<span><%= review.description %></span>
						</h4>
					</span>
			<% end %>
				
			</div>
		</section>
	</div>
	<div class="col-md-3">
		<aside>
			<h2>Latest bids</h2>
			<div class="list-group">
				<% @my_bids.each do |bid| %>
					
					<span class="list-group-item">
						<h5>
							<%= bid.amount %>
							<span><%= bid.product.title %></span>
						</h5>	
					</span>
					
				<% end %>

			</div>
		</aside>
	</div>
</div>